/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as DocumentDocumentIdIndexRouteImport } from './routes/document/$documentId/index'
import { Route as DocumentDocumentIdMainRouteImport } from './routes/document/$documentId/main'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminDocumentsNewRouteImport } from './routes/_admin/documents.new'
import { Route as AdminDocumentsDocumentIdRouteImport } from './routes/_admin/documents.$documentId'
import { Route as AdminDocumentsDocumentIdIndexRouteImport } from './routes/_admin/documents.$documentId.index'
import { Route as DocumentDocumentIdMainRawRouteImport } from './routes/document/$documentId/main/raw'
import { Route as AdminDocumentsDocumentIdEditRouteImport } from './routes/_admin/documents.$documentId.edit'
import { Route as DocumentDocumentIdCommitCommitHashIndexRouteImport } from './routes/document/$documentId/commit/$commitHash/index'
import { Route as DocumentDocumentIdCommitCommitHashRawRouteImport } from './routes/document/$documentId/commit/$commitHash/raw'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const DocumentDocumentIdIndexRoute = DocumentDocumentIdIndexRouteImport.update({
  id: '/document/$documentId/',
  path: '/document/$documentId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentDocumentIdMainRoute = DocumentDocumentIdMainRouteImport.update({
  id: '/document/$documentId/main',
  path: '/document/$documentId/main',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsNewRoute = AdminDocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsDocumentIdRoute =
  AdminDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDocumentsDocumentIdIndexRoute =
  AdminDocumentsDocumentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminDocumentsDocumentIdRoute,
  } as any)
const DocumentDocumentIdMainRawRoute =
  DocumentDocumentIdMainRawRouteImport.update({
    id: '/raw',
    path: '/raw',
    getParentRoute: () => DocumentDocumentIdMainRoute,
  } as any)
const AdminDocumentsDocumentIdEditRoute =
  AdminDocumentsDocumentIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminDocumentsDocumentIdRoute,
  } as any)
const DocumentDocumentIdCommitCommitHashIndexRoute =
  DocumentDocumentIdCommitCommitHashIndexRouteImport.update({
    id: '/document/$documentId/commit/$commitHash/',
    path: '/document/$documentId/commit/$commitHash/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentDocumentIdCommitCommitHashRawRoute =
  DocumentDocumentIdCommitCommitHashRawRouteImport.update({
    id: '/document/$documentId/commit/$commitHash/raw',
    path: '/document/$documentId/commit/$commitHash/raw',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/documents/$documentId': typeof AdminDocumentsDocumentIdRouteWithChildren
  '/documents/new': typeof AdminDocumentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/document/$documentId/main': typeof DocumentDocumentIdMainRouteWithChildren
  '/document/$documentId/': typeof DocumentDocumentIdIndexRoute
  '/documents/$documentId/edit': typeof AdminDocumentsDocumentIdEditRoute
  '/document/$documentId/main/raw': typeof DocumentDocumentIdMainRawRoute
  '/documents/$documentId/': typeof AdminDocumentsDocumentIdIndexRoute
  '/document/$documentId/commit/$commitHash/raw': typeof DocumentDocumentIdCommitCommitHashRawRoute
  '/document/$documentId/commit/$commitHash/': typeof DocumentDocumentIdCommitCommitHashIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/documents/new': typeof AdminDocumentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/document/$documentId/main': typeof DocumentDocumentIdMainRouteWithChildren
  '/document/$documentId': typeof DocumentDocumentIdIndexRoute
  '/documents/$documentId/edit': typeof AdminDocumentsDocumentIdEditRoute
  '/document/$documentId/main/raw': typeof DocumentDocumentIdMainRawRoute
  '/documents/$documentId': typeof AdminDocumentsDocumentIdIndexRoute
  '/document/$documentId/commit/$commitHash/raw': typeof DocumentDocumentIdCommitCommitHashRawRoute
  '/document/$documentId/commit/$commitHash': typeof DocumentDocumentIdCommitCommitHashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_admin/documents/$documentId': typeof AdminDocumentsDocumentIdRouteWithChildren
  '/_admin/documents/new': typeof AdminDocumentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/document/$documentId/main': typeof DocumentDocumentIdMainRouteWithChildren
  '/document/$documentId/': typeof DocumentDocumentIdIndexRoute
  '/_admin/documents/$documentId/edit': typeof AdminDocumentsDocumentIdEditRoute
  '/document/$documentId/main/raw': typeof DocumentDocumentIdMainRawRoute
  '/_admin/documents/$documentId/': typeof AdminDocumentsDocumentIdIndexRoute
  '/document/$documentId/commit/$commitHash/raw': typeof DocumentDocumentIdCommitCommitHashRawRoute
  '/document/$documentId/commit/$commitHash/': typeof DocumentDocumentIdCommitCommitHashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/documents/$documentId'
    | '/documents/new'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/document/$documentId/main'
    | '/document/$documentId/'
    | '/documents/$documentId/edit'
    | '/document/$documentId/main/raw'
    | '/documents/$documentId/'
    | '/document/$documentId/commit/$commitHash/raw'
    | '/document/$documentId/commit/$commitHash/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/documents/new'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/document/$documentId/main'
    | '/document/$documentId'
    | '/documents/$documentId/edit'
    | '/document/$documentId/main/raw'
    | '/documents/$documentId'
    | '/document/$documentId/commit/$commitHash/raw'
    | '/document/$documentId/commit/$commitHash'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/login'
    | '/_admin/dashboard'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/_admin/documents/$documentId'
    | '/_admin/documents/new'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/document/$documentId/main'
    | '/document/$documentId/'
    | '/_admin/documents/$documentId/edit'
    | '/document/$documentId/main/raw'
    | '/_admin/documents/$documentId/'
    | '/document/$documentId/commit/$commitHash/raw'
    | '/document/$documentId/commit/$commitHash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DocumentDocumentIdMainRoute: typeof DocumentDocumentIdMainRouteWithChildren
  DocumentDocumentIdIndexRoute: typeof DocumentDocumentIdIndexRoute
  DocumentDocumentIdCommitCommitHashRawRoute: typeof DocumentDocumentIdCommitCommitHashRawRoute
  DocumentDocumentIdCommitCommitHashIndexRoute: typeof DocumentDocumentIdCommitCommitHashIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/document/$documentId/': {
      id: '/document/$documentId/'
      path: '/document/$documentId'
      fullPath: '/document/$documentId/'
      preLoaderRoute: typeof DocumentDocumentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/$documentId/main': {
      id: '/document/$documentId/main'
      path: '/document/$documentId/main'
      fullPath: '/document/$documentId/main'
      preLoaderRoute: typeof DocumentDocumentIdMainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/documents/new': {
      id: '/_admin/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AdminDocumentsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/documents/$documentId': {
      id: '/_admin/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AdminDocumentsDocumentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/documents/$documentId/': {
      id: '/_admin/documents/$documentId/'
      path: '/'
      fullPath: '/documents/$documentId/'
      preLoaderRoute: typeof AdminDocumentsDocumentIdIndexRouteImport
      parentRoute: typeof AdminDocumentsDocumentIdRoute
    }
    '/document/$documentId/main/raw': {
      id: '/document/$documentId/main/raw'
      path: '/raw'
      fullPath: '/document/$documentId/main/raw'
      preLoaderRoute: typeof DocumentDocumentIdMainRawRouteImport
      parentRoute: typeof DocumentDocumentIdMainRoute
    }
    '/_admin/documents/$documentId/edit': {
      id: '/_admin/documents/$documentId/edit'
      path: '/edit'
      fullPath: '/documents/$documentId/edit'
      preLoaderRoute: typeof AdminDocumentsDocumentIdEditRouteImport
      parentRoute: typeof AdminDocumentsDocumentIdRoute
    }
    '/document/$documentId/commit/$commitHash/': {
      id: '/document/$documentId/commit/$commitHash/'
      path: '/document/$documentId/commit/$commitHash'
      fullPath: '/document/$documentId/commit/$commitHash/'
      preLoaderRoute: typeof DocumentDocumentIdCommitCommitHashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/$documentId/commit/$commitHash/raw': {
      id: '/document/$documentId/commit/$commitHash/raw'
      path: '/document/$documentId/commit/$commitHash/raw'
      fullPath: '/document/$documentId/commit/$commitHash/raw'
      preLoaderRoute: typeof DocumentDocumentIdCommitCommitHashRawRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminDocumentsDocumentIdRouteChildren {
  AdminDocumentsDocumentIdEditRoute: typeof AdminDocumentsDocumentIdEditRoute
  AdminDocumentsDocumentIdIndexRoute: typeof AdminDocumentsDocumentIdIndexRoute
}

const AdminDocumentsDocumentIdRouteChildren: AdminDocumentsDocumentIdRouteChildren =
  {
    AdminDocumentsDocumentIdEditRoute: AdminDocumentsDocumentIdEditRoute,
    AdminDocumentsDocumentIdIndexRoute: AdminDocumentsDocumentIdIndexRoute,
  }

const AdminDocumentsDocumentIdRouteWithChildren =
  AdminDocumentsDocumentIdRoute._addFileChildren(
    AdminDocumentsDocumentIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDocumentsDocumentIdRoute: typeof AdminDocumentsDocumentIdRouteWithChildren
  AdminDocumentsNewRoute: typeof AdminDocumentsNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDocumentsDocumentIdRoute: AdminDocumentsDocumentIdRouteWithChildren,
  AdminDocumentsNewRoute: AdminDocumentsNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DocumentDocumentIdMainRouteChildren {
  DocumentDocumentIdMainRawRoute: typeof DocumentDocumentIdMainRawRoute
}

const DocumentDocumentIdMainRouteChildren: DocumentDocumentIdMainRouteChildren =
  {
    DocumentDocumentIdMainRawRoute: DocumentDocumentIdMainRawRoute,
  }

const DocumentDocumentIdMainRouteWithChildren =
  DocumentDocumentIdMainRoute._addFileChildren(
    DocumentDocumentIdMainRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DocumentDocumentIdMainRoute: DocumentDocumentIdMainRouteWithChildren,
  DocumentDocumentIdIndexRoute: DocumentDocumentIdIndexRoute,
  DocumentDocumentIdCommitCommitHashRawRoute:
    DocumentDocumentIdCommitCommitHashRawRoute,
  DocumentDocumentIdCommitCommitHashIndexRoute:
    DocumentDocumentIdCommitCommitHashIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
